# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import common_pb2 as common__pb2
from . import index_coord_pb2 as index__coord__pb2
from . import internal_pb2 as internal__pb2
from . import milvus_pb2 as milvus__pb2


class IndexCoordStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetComponentStates = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/GetComponentStates',
                request_serializer=milvus__pb2.GetComponentStatesRequest.SerializeToString,
                response_deserializer=milvus__pb2.ComponentStates.FromString,
                )
        self.GetStatisticsChannel = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/GetStatisticsChannel',
                request_serializer=internal__pb2.GetStatisticsChannelRequest.SerializeToString,
                response_deserializer=milvus__pb2.StringResponse.FromString,
                )
        self.CreateIndex = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/CreateIndex',
                request_serializer=index__coord__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                )
        self.AlterIndex = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/AlterIndex',
                request_serializer=index__coord__pb2.AlterIndexRequest.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                )
        self.GetIndexState = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/GetIndexState',
                request_serializer=index__coord__pb2.GetIndexStateRequest.SerializeToString,
                response_deserializer=index__coord__pb2.GetIndexStateResponse.FromString,
                )
        self.GetSegmentIndexState = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/GetSegmentIndexState',
                request_serializer=index__coord__pb2.GetSegmentIndexStateRequest.SerializeToString,
                response_deserializer=index__coord__pb2.GetSegmentIndexStateResponse.FromString,
                )
        self.GetIndexInfos = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/GetIndexInfos',
                request_serializer=index__coord__pb2.GetIndexInfoRequest.SerializeToString,
                response_deserializer=index__coord__pb2.GetIndexInfoResponse.FromString,
                )
        self.DropIndex = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/DropIndex',
                request_serializer=index__coord__pb2.DropIndexRequest.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                )
        self.DescribeIndex = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/DescribeIndex',
                request_serializer=index__coord__pb2.DescribeIndexRequest.SerializeToString,
                response_deserializer=index__coord__pb2.DescribeIndexResponse.FromString,
                )
        self.GetIndexStatistics = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/GetIndexStatistics',
                request_serializer=index__coord__pb2.GetIndexStatisticsRequest.SerializeToString,
                response_deserializer=index__coord__pb2.GetIndexStatisticsResponse.FromString,
                )
        self.GetIndexBuildProgress = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/GetIndexBuildProgress',
                request_serializer=index__coord__pb2.GetIndexBuildProgressRequest.SerializeToString,
                response_deserializer=index__coord__pb2.GetIndexBuildProgressResponse.FromString,
                )
        self.ShowConfigurations = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/ShowConfigurations',
                request_serializer=internal__pb2.ShowConfigurationsRequest.SerializeToString,
                response_deserializer=internal__pb2.ShowConfigurationsResponse.FromString,
                )
        self.GetMetrics = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/GetMetrics',
                request_serializer=milvus__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=milvus__pb2.GetMetricsResponse.FromString,
                )
        self.CheckHealth = channel.unary_unary(
                '/milvus.proto.index.IndexCoord/CheckHealth',
                request_serializer=milvus__pb2.CheckHealthRequest.SerializeToString,
                response_deserializer=milvus__pb2.CheckHealthResponse.FromString,
                )


class IndexCoordServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetComponentStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatisticsChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexState(self, request, context):
        """Deprecated: use DescribeIndex instead
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSegmentIndexState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexInfos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexBuildProgress(self, request, context):
        """Deprecated: use DescribeIndex instead
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowConfigurations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """https://wiki.lfaidata.foundation/display/MIL/MEP+8+--+Add+metrics+for+proxy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexCoordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetComponentStates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComponentStates,
                    request_deserializer=milvus__pb2.GetComponentStatesRequest.FromString,
                    response_serializer=milvus__pb2.ComponentStates.SerializeToString,
            ),
            'GetStatisticsChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatisticsChannel,
                    request_deserializer=internal__pb2.GetStatisticsChannelRequest.FromString,
                    response_serializer=milvus__pb2.StringResponse.SerializeToString,
            ),
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=index__coord__pb2.CreateIndexRequest.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'AlterIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterIndex,
                    request_deserializer=index__coord__pb2.AlterIndexRequest.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'GetIndexState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexState,
                    request_deserializer=index__coord__pb2.GetIndexStateRequest.FromString,
                    response_serializer=index__coord__pb2.GetIndexStateResponse.SerializeToString,
            ),
            'GetSegmentIndexState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSegmentIndexState,
                    request_deserializer=index__coord__pb2.GetSegmentIndexStateRequest.FromString,
                    response_serializer=index__coord__pb2.GetSegmentIndexStateResponse.SerializeToString,
            ),
            'GetIndexInfos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexInfos,
                    request_deserializer=index__coord__pb2.GetIndexInfoRequest.FromString,
                    response_serializer=index__coord__pb2.GetIndexInfoResponse.SerializeToString,
            ),
            'DropIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DropIndex,
                    request_deserializer=index__coord__pb2.DropIndexRequest.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'DescribeIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeIndex,
                    request_deserializer=index__coord__pb2.DescribeIndexRequest.FromString,
                    response_serializer=index__coord__pb2.DescribeIndexResponse.SerializeToString,
            ),
            'GetIndexStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexStatistics,
                    request_deserializer=index__coord__pb2.GetIndexStatisticsRequest.FromString,
                    response_serializer=index__coord__pb2.GetIndexStatisticsResponse.SerializeToString,
            ),
            'GetIndexBuildProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexBuildProgress,
                    request_deserializer=index__coord__pb2.GetIndexBuildProgressRequest.FromString,
                    response_serializer=index__coord__pb2.GetIndexBuildProgressResponse.SerializeToString,
            ),
            'ShowConfigurations': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowConfigurations,
                    request_deserializer=internal__pb2.ShowConfigurationsRequest.FromString,
                    response_serializer=internal__pb2.ShowConfigurationsResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=milvus__pb2.GetMetricsRequest.FromString,
                    response_serializer=milvus__pb2.GetMetricsResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=milvus__pb2.CheckHealthRequest.FromString,
                    response_serializer=milvus__pb2.CheckHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'milvus.proto.index.IndexCoord', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IndexCoord(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetComponentStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/GetComponentStates',
            milvus__pb2.GetComponentStatesRequest.SerializeToString,
            milvus__pb2.ComponentStates.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatisticsChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/GetStatisticsChannel',
            internal__pb2.GetStatisticsChannelRequest.SerializeToString,
            milvus__pb2.StringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/CreateIndex',
            index__coord__pb2.CreateIndexRequest.SerializeToString,
            common__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AlterIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/AlterIndex',
            index__coord__pb2.AlterIndexRequest.SerializeToString,
            common__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIndexState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/GetIndexState',
            index__coord__pb2.GetIndexStateRequest.SerializeToString,
            index__coord__pb2.GetIndexStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSegmentIndexState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/GetSegmentIndexState',
            index__coord__pb2.GetSegmentIndexStateRequest.SerializeToString,
            index__coord__pb2.GetSegmentIndexStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIndexInfos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/GetIndexInfos',
            index__coord__pb2.GetIndexInfoRequest.SerializeToString,
            index__coord__pb2.GetIndexInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DropIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/DropIndex',
            index__coord__pb2.DropIndexRequest.SerializeToString,
            common__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/DescribeIndex',
            index__coord__pb2.DescribeIndexRequest.SerializeToString,
            index__coord__pb2.DescribeIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIndexStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/GetIndexStatistics',
            index__coord__pb2.GetIndexStatisticsRequest.SerializeToString,
            index__coord__pb2.GetIndexStatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIndexBuildProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/GetIndexBuildProgress',
            index__coord__pb2.GetIndexBuildProgressRequest.SerializeToString,
            index__coord__pb2.GetIndexBuildProgressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShowConfigurations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/ShowConfigurations',
            internal__pb2.ShowConfigurationsRequest.SerializeToString,
            internal__pb2.ShowConfigurationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/GetMetrics',
            milvus__pb2.GetMetricsRequest.SerializeToString,
            milvus__pb2.GetMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexCoord/CheckHealth',
            milvus__pb2.CheckHealthRequest.SerializeToString,
            milvus__pb2.CheckHealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class IndexNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetComponentStates = channel.unary_unary(
                '/milvus.proto.index.IndexNode/GetComponentStates',
                request_serializer=milvus__pb2.GetComponentStatesRequest.SerializeToString,
                response_deserializer=milvus__pb2.ComponentStates.FromString,
                )
        self.GetStatisticsChannel = channel.unary_unary(
                '/milvus.proto.index.IndexNode/GetStatisticsChannel',
                request_serializer=internal__pb2.GetStatisticsChannelRequest.SerializeToString,
                response_deserializer=milvus__pb2.StringResponse.FromString,
                )
        self.CreateJob = channel.unary_unary(
                '/milvus.proto.index.IndexNode/CreateJob',
                request_serializer=index__coord__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                )
        self.QueryJobs = channel.unary_unary(
                '/milvus.proto.index.IndexNode/QueryJobs',
                request_serializer=index__coord__pb2.QueryJobsRequest.SerializeToString,
                response_deserializer=index__coord__pb2.QueryJobsResponse.FromString,
                )
        self.DropJobs = channel.unary_unary(
                '/milvus.proto.index.IndexNode/DropJobs',
                request_serializer=index__coord__pb2.DropJobsRequest.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                )
        self.GetJobStats = channel.unary_unary(
                '/milvus.proto.index.IndexNode/GetJobStats',
                request_serializer=index__coord__pb2.GetJobStatsRequest.SerializeToString,
                response_deserializer=index__coord__pb2.GetJobStatsResponse.FromString,
                )
        self.ShowConfigurations = channel.unary_unary(
                '/milvus.proto.index.IndexNode/ShowConfigurations',
                request_serializer=internal__pb2.ShowConfigurationsRequest.SerializeToString,
                response_deserializer=internal__pb2.ShowConfigurationsResponse.FromString,
                )
        self.GetMetrics = channel.unary_unary(
                '/milvus.proto.index.IndexNode/GetMetrics',
                request_serializer=milvus__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=milvus__pb2.GetMetricsResponse.FromString,
                )


class IndexNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetComponentStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatisticsChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowConfigurations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """https://wiki.lfaidata.foundation/display/MIL/MEP+8+--+Add+metrics+for+proxy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetComponentStates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComponentStates,
                    request_deserializer=milvus__pb2.GetComponentStatesRequest.FromString,
                    response_serializer=milvus__pb2.ComponentStates.SerializeToString,
            ),
            'GetStatisticsChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatisticsChannel,
                    request_deserializer=internal__pb2.GetStatisticsChannelRequest.FromString,
                    response_serializer=milvus__pb2.StringResponse.SerializeToString,
            ),
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=index__coord__pb2.CreateJobRequest.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'QueryJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryJobs,
                    request_deserializer=index__coord__pb2.QueryJobsRequest.FromString,
                    response_serializer=index__coord__pb2.QueryJobsResponse.SerializeToString,
            ),
            'DropJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.DropJobs,
                    request_deserializer=index__coord__pb2.DropJobsRequest.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'GetJobStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStats,
                    request_deserializer=index__coord__pb2.GetJobStatsRequest.FromString,
                    response_serializer=index__coord__pb2.GetJobStatsResponse.SerializeToString,
            ),
            'ShowConfigurations': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowConfigurations,
                    request_deserializer=internal__pb2.ShowConfigurationsRequest.FromString,
                    response_serializer=internal__pb2.ShowConfigurationsResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=milvus__pb2.GetMetricsRequest.FromString,
                    response_serializer=milvus__pb2.GetMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'milvus.proto.index.IndexNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IndexNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetComponentStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexNode/GetComponentStates',
            milvus__pb2.GetComponentStatesRequest.SerializeToString,
            milvus__pb2.ComponentStates.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatisticsChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexNode/GetStatisticsChannel',
            internal__pb2.GetStatisticsChannelRequest.SerializeToString,
            milvus__pb2.StringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexNode/CreateJob',
            index__coord__pb2.CreateJobRequest.SerializeToString,
            common__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexNode/QueryJobs',
            index__coord__pb2.QueryJobsRequest.SerializeToString,
            index__coord__pb2.QueryJobsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DropJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexNode/DropJobs',
            index__coord__pb2.DropJobsRequest.SerializeToString,
            common__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexNode/GetJobStats',
            index__coord__pb2.GetJobStatsRequest.SerializeToString,
            index__coord__pb2.GetJobStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShowConfigurations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexNode/ShowConfigurations',
            internal__pb2.ShowConfigurationsRequest.SerializeToString,
            internal__pb2.ShowConfigurationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/milvus.proto.index.IndexNode/GetMetrics',
            milvus__pb2.GetMetricsRequest.SerializeToString,
            milvus__pb2.GetMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
